replace hardcode

diff --git a/install-console b/install-console
--- a/install-console
+++ b/install-console
@@ -12,18 +12,18 @@ then
   cd $XSCE_DIR
 fi
 
-if [ ! -f xsce.yml ]
-then
- echo "XSCE Playbook not found."
- echo "Please run this command from the top level of the git repo."
- echo "Exiting."
- exit
-fi
-
 PLAYBOOK="xsce-base.yml"
 INVENTORY="ansible_hosts"
 SELINUX_BEFORE=""
 SELINUX_AFTER=""
+
+if [ ! -f $PLAYBOOK ]
+then
+ echo "XSCE Playbook not found."
+ echo "Please run this command from the top level of the git repo."
+ echo "Exiting."
+ exit 1
+fi
 
 if [ -f /etc/selinux/config ]
 then
