Check for apache before creating it in moodle

diff --git a/roles/moodle/templates/moodle-xs-init b/roles/moodle/templates/moodle-xs-init
--- a/roles/moodle/templates/moodle-xs-init
+++ b/roles/moodle/templates/moodle-xs-init
@@ -27,7 +27,10 @@ start() {
 		pushd /var/www/moodle/web
 
                 # Attempt to create an 'apache' user in PostgreSQL
-                su  -c 'createuser -SRD apache' postgres || echo 'Could not create apache user (exists already?)'
+                su postgres -c "psql postgres -tAc \"SELECT 'OK' FROM pg_roles WHERE rolname='apache'\"" | grep 'OK'
+                if [[ $? -ne 0 ]]; then
+                    su -c 'createuser -SRD apache' postgres || echo 'Could not create apache user (exists already?)'
+                fi
 
                 # attempt to create a database
                 su -c 'createdb -O apache -E utf8 -T template0 moodle-xs' postgres || echo 'Could not create moodle-xs DB (exists already?)'
