added exit function after a Yum error so that state is correct, and user not decieved that it worked when it didn't

diff --git a/scripts/xs-setup-functions b/scripts/xs-setup-functions
--- a/scripts/xs-setup-functions
+++ b/scripts/xs-setup-functions
@@ -23,6 +23,7 @@ SETUPSTATEDIR=/etc/sysconfig/olpc-scripts/setup.d/installed
 DEFAULTUSER='admin'
 DEFAULTPASSWORD='12admin'
 ISXO=`[ -f /proc/device-tree/mfg-data/MN ] && echo 1 || echo 0`
+YUMERROR=10
 
 function activity-server()
 {
@@ -32,7 +33,6 @@ function activity-server()
         touch SETUPSTATEDIR/activity-server
         ;;
     "no")
-        yum -y erase   activity-server 2>&1 | tee -a $LOG
         rm $SETUPSTATEDIR/activity-server
         ;;
     esac
@@ -43,12 +43,15 @@ function avahi()
 	case "$1" in
 	"yes")
         yum -y install nss-mdns avahi avahi-tools avahi-ui 2>&1 | tee -a $LOG
+        if [ $? -ne 0 ] ; then
+            echo "\n\nYum returned an error\n\n" | tee -a $LOG
+            exit $YUMERROR
+        fi
 		systemctl enable avahi-daemon.service 2>&1 | tee -a $LOG
         touch $SETUPSTATEDIR/avahi
         ;;
 	"no")
 		systemctl disable avahi-daemon.service 2>&1 | tee -a $LOG
-        #yum -y erase nss-mdns avahi avahi-tools avahi-ui
         rm $SETUPSTATEDIR/avahi
         ;;
 	esac
@@ -59,12 +62,15 @@ function dhcpd()
 	case "$1" in
 	"yes")
         yum -y install dhcp 2>&1 | tee -a $LOG
+        if [ $? -ne 0 ] ; then
+            echo "\n\nYum returned an error\n\n" | tee -a $LOG
+            exit $YUMERROR
+        fi
 		systemctl enable dhcpd.service 2>&1 | tee -a $LOG
         touch $SETUPSTATEDIR/dhcpd
         ;;
 	"no")
 		systemctl disable dhcpd.service 2>&1 | tee -a $LOG
-        yum -y erase dhcp 2>&1 | tee -a $LOG
         rm $SETUPSTATEDIR/dhcpd
         ;;
 	esac
@@ -86,6 +92,10 @@ function set-etckeeper()
         if [ ! -d /etc/.git ]; then
             pushd /etc
             yum -y install etckeeper
+            if [ $? -ne 0 ] ; then
+                echo "\n\nYum returned an error\n\n" | tee -a $LOG
+                exit $YUMERROR
+            fi
             etckeeper init
             etckeeper commit -m "Initial checkin"
             git gc
@@ -109,6 +119,10 @@ function ejabberd()
 	case "$1" in
 	"yes")
         yum -y install ejabberd 2>&1 | tee -a $LOG
+        if [ $? -ne 0 ] ; then
+            echo "\n\nYum returned an error\n\n" | tee -a $LOG
+            exit $YUMERROR
+        fi
 
 		# and set it to autostart
         cp /etc/systemd/system/ejabberd-xs.service.in \
@@ -119,7 +133,6 @@ function ejabberd()
 		;;
 	"no")
 		systemctl disable ejabberd.service 2>&1 | tee -a $LOG
-        yum -y erase ejabberd 2>&1 | tee -a $LOG
         rm $SETUPSTATEDIR/ejabberd
 		;;
 	esac
@@ -151,6 +164,10 @@ function httpd()
 	case "$1" in
 	"yes")
 		yum -y install httpd php  2>&1 | tee -a $LOG
+        if [ $? -ne 0 ] ; then
+            echo "\n\nYum returned an error\n\n" | tee -a $LOG
+            exit $YUMERROR
+        fi
         cp -p /etc/httpd/conf/httpd-xs.conf.in /etc/httpd/conf/httpd-xs.conf
 		# Choose a config depending on memory
 		MEMSIZE=$(grep '^MemTotal' /proc/meminfo | grep -oP '\d+')
@@ -179,7 +196,6 @@ function httpd()
 		;;
 	"no")
 		systemctl disable httpd.service 2>&1 | tee -a $LOG
-        yum -y erase httpd 2>&1 | tee -a $LOG
         rm $SETUPSTATEDIR/httpd
 		;;
 	esac
@@ -191,9 +207,15 @@ function idmgr()
 	"yes")
         yum -y install idmgr ds-backup-server \
                 xs-rsync xinetd 2>&1 | tee -a $LOG
+        if [ $? -ne 0 ] ; then
+            echo "\n\nYum returned an error\n\n" | tee -a $LOG
+            exit $YUMERROR
+        fi
+
         #set up the sqlite database for idmgr
         /etc/sysconfig/olpc-scripts/setup.d/idmgr
-        #we'll leave the script in place and call it from systemd
+        
+        #long term, change the idmgr package
         cp /etc/init.d/idmgr /usr/libexec/idmgr.init
         
         #execute the xs-rsync setup script
@@ -212,7 +234,6 @@ function idmgr()
         ;;
 	"no")
 		systemctl disable idmgr.service 2>&1 | tee -a $LOG
-        yum -y erase idmgr ds-backup xs-rsync  2>&1 | tee -a $LOG
         rm $SETUPSTATEDIR/idmgr
         ;;
 	esac
@@ -226,13 +247,16 @@ function manpages()
         sed -i -c  's/%_excludedocs 1/%_excludedocs 0/' /etc/rpm/macros.imgcreate
         set -e
 		yum -y install man-pages man-db man 2>&1 | tee -a $LOG
+        if [ $? -ne 0 ] ; then
+            echo "\n\nYum returned an error\n\n" | tee -a $LOG
+            exit $YUMERROR
+        fi
         touch $SETUPSTATEDIR/manpages
         ;;
 	"no")
         set +e
         sed -i -c  's/%_excludedocs 0/%_excludedocs 1/' /etc/rpm/macros.imgcreate
         set -e
-		yum -y erase  man-pages man-db man 2>&1 | tee -a $LOG
         rm -rf /usr/share/man
         rm $SETUPSTATEDIR/manpages
         ;;
@@ -244,11 +268,14 @@ function mlocate()
 	case "$1" in
 	"yes")
         yum -y install mlocate 2>&1 | tee -a $LOG
+        if [ $? -ne 0 ] ; then
+            echo "\n\nYum returned an error\n\n" | tee -a $LOG
+            exit $YUMERROR
+        fi
         updatedb
         touch $SETUPSTATEDIR/mlocate
         ;;
 	"no")
-        yum -y erase mlocate 2>&1 | tee -a $LOG
         rm $SETUPSTATEDIR/mlocate
         ;;
 	esac
@@ -259,12 +286,15 @@ function moodle()
 	case "$1" in
 	"yes")
         yum -y install moodle 2>&1 | tee -a $LOG
+        if [ $? -ne 0 ] ; then
+            echo "\n\nYum returned an error\n\n" | tee -a $LOG
+            exit $YUMERROR
+        fi
 		systemctl enable moddle.service 2>&1 | tee -a $LOG
         touch $SETUPSTATEDIR/moodle
         ;;
 	"no")
 		systemctl disable moddle.service 2>&1 | tee -a $LOG
-        yum -y erase moodle 2>&1 | tee -a $LOG
         rm $SETUPSTATEDIR/moodle
         ;;
 	esac
@@ -275,6 +305,10 @@ function moodle-xs()
 	case "$1" in
 	"yes")
         yum -y install moodle-xs 2>&1 | tee -a $LOG
+        if [ $? -ne 0 ] ; then
+            echo "\n\nYum returned an error\n\n" | tee -a $LOG
+            exit $YUMERROR
+        fi
         cp -p /etc/systemd/system/moodle-xs.service.in \
                 /etc/systemd/system/moodle-xs.service
         cp -p /etc/sysconfig/olpc-scripts/moodle-xs-init.in \
@@ -286,7 +320,6 @@ function moodle-xs()
         ;;
 	"no")
 		systemctl disable moddle-xs.service 2>&1 | tee -a $LOG
-        yum -y erase moodle-xs 2>&1 | tee -a $LOG
         rm $SETUPSTATEDIR/moodle-xs
         ;;
 	esac
@@ -297,6 +330,10 @@ function named()
 	case "$1" in
 	"yes")
         yum -y install bind bind-utils 2>&1 | tee -a $LOG
+        if [ $? -ne 0 ] ; then
+            echo "\n\nYum returned an error\n\n" | tee -a $LOG
+            exit $YUMERROR
+        fi
         #if xs data files are installed before bind, named user doesn't exist,
         #   and group ownership is set to root, which uer named cannot read
         if [ -d /var/named-xs ]; then
@@ -312,7 +349,6 @@ function named()
 		systemctl disable named.service 2>&1 | tee -a $LOG
         #let the dhclinet control the name resolution normally
         rm /etc/sysconfig/olpc-scripts/resolv.conf
-        yum -y erase bind 2>&1 | tee -a $LOG
         rm $SETUPSTATEDIR/named
         ;;
 	esac
@@ -325,6 +361,10 @@ function pathagar()
         httpd yes
         yum -y mod_python mod_wsgi  python-django Django \
                 python-setuptools sqlite django-tagging
+        if [ $? -ne 0 ] ; then
+            echo "\n\nYum returned an error\n\n" | tee -a $LOG
+            exit $YUMERROR
+        fi
         adduser bookserver
         cd /home/bookserver
         git clone git://github.com/johnsensile/django-sendfile.git
@@ -351,6 +391,10 @@ function postgresql()
 	case "$1" in
 	"yes")
         yum -y install postgresql postgresql-server 2>&1 | tee -a $LOG
+        if [ $? -ne 0 ] ; then
+            echo "\n\nYum returned an error\n\n" | tee -a $LOG
+            exit $YUMERROR
+        fi
         cp /etc/systemd/system/postgresql-xs.service.in \
                 /etc/systemd/system/postgresql-xs.service
 		systemctl enable postgresql-xs.service 2>&1 | tee -a $LOG
@@ -372,7 +416,6 @@ function postgresql()
 		;;
 	"no")
 		systemctl disable postgresql-xs.service 2>&1 | tee -a $LOG
-        yum -y erase postgresql  posstgresql-server 2>&1 | tee -a $LOG
         rm $SETUPSTATEDIR/postgresql
 		;;
 	esac
@@ -383,6 +426,10 @@ function squid()
 	case "$1" in
 	"yes")
         yum -y install squid 2>&1 | tee -a $LOG
+        if [ $? -ne 0 ] ; then
+            echo "\n\nYum returned an error\n\n" | tee -a $LOG
+            exit $YUMERROR
+        fi
         #create the cache directories
         squid -z
         ## Update flag for httpd cache
@@ -398,7 +445,6 @@ function squid()
         ;;
     "no")
         systemctl disable squid.service 2>&1 | tee -a $LOG
-        yum -y erase squid 2>&1 | tee -a $LOG
         rm $SETUPSTATEDIR/squid
         ;;
     esac
@@ -409,7 +455,15 @@ function vnc()
 	case "$1" in
 	"yes")
         yum -y install tigervnc-server novnc 2>&1 | tee -a $LOG
+        if [ $? -ne 0 ] ; then
+            echo "\n\nYum returned an error\n\n" | tee -a $LOG
+            exit $YUMERROR
+        fi
         yum -y groupinstall XFCE  2>&1 | tee -a $LOG
+        if [ $? -ne 0 ] ; then
+            echo "\n\nYum returned an error\n\n" | tee -a $LOG
+            exit $YUMERROR
+        fi
         #or yum install x11vnc-javaviewers | tee -a $LOG
         cp -p /lib/systemd/system/vncserver\@.service /etc/systemd/system
         sed -i -c 's/<USER>/$DEFAULTUSER/' /etc/systemd/system/vncserver\@.service
@@ -432,7 +486,6 @@ function vnc()
         ;;
 	"no")
 		systemctl disable vncserver\@.service 2>&1 | tee -a $LOG
-        yum -y erase tigervnc-server novnc2>&1 | tee -a $LOG
         rm $SETUPSTATEDIR/vnc
         ;;
 	esac
@@ -444,6 +497,10 @@ function webdav()
 	"yes")
         cp /etc/httpd/conf.d/webdav.conf.in /etc/httpd/conf.d/webdav.conf
         yum -y install cadaver
+        if [ $? -ne 0 ] ; then
+            echo "\n\nYum returned an error\n\n" | tee -a $LOG
+            exit $YUMERROR
+        fi
         mkdir -p /library/webdav
         chown apache:apache /library/webdav
         htpasswd -cb /etc/httpd/webdav.users.pwd $DEFAULTUSER $DEFAULTPASSWORD
@@ -477,10 +534,13 @@ function xs-security()
 	case "$1" in
     "yes")
         yum -y install  xs-tools olpc-bios-crypto bitfrost xs-activation 2>&1 | tee -a $LOG
+        if [ $? -ne 0 ] ; then
+            echo "\n\nYum returned an error\n\n" | tee -a $LOG
+            exit $YUMERROR
+        fi
         touch $SETUPSTATEDIR/xs-security
         ;;
     "no")
-        yum -y erase   xs-tools olpc-bios-crypto bitfrost xs-activation 2>&1 | tee -a $LOG
         rm $SETUPSTATEDIR/xs-security
         ;;
     esac
@@ -598,6 +658,10 @@ function do_first()
         
         #following packages are the core set of packages installed on all xs servers
         yum -y install  syck rssh mtd-utils acpid  2>&1 | tee -a $LOG
+        if [ $? -ne 0 ] ; then
+            echo "\n\nYum returned an error\n\n" | tee -a $LOG
+            exit $YUMERROR
+        fi
         #copy .bashrc to /root
         cp -p /home/olpc/.bashrc /root
         
